backend:
  name: github
  repo: GoldenJDM/GoldenJDM-website
  branch: main

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "📝 وبلاگ"
    folder: "fa/blog/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "تاریخ", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "خلاصه", name: "excerpt", widget: "text", required: false }
      - { label: "تگ‌ها", name: "tags", widget: "list", default: ["عمومی"], required: false }
      - { label: "متن اصلی", name: "body", widget: "markdown" }
